# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# NOTE: DO *NOT* EDIT THIS FILE.  IT IS GENERATED.
# PLEASE UPDATE Dockerfile.txt INSTEAD OF THIS FILE
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
FROM selenium/standalone-firefox:3.4.0-chromium
LABEL authors=SeleniumHQ

USER root

#==============================
# Scripts to run Selenium Node
#==============================
CMD ["/opt/bin/selenium_standalone_with_vnc.sh"]

EXPOSE 5900
