# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# NOTE: DO *NOT* EDIT THIS FILE.  IT IS GENERATED.
# PLEASE UPDATE Dockerfile.txt INSTEAD OF THIS FILE
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
FROM selenium/node-chrome:local
LABEL authors=SeleniumHQ

USER root

#====================================
# Scripts to run Selenium Standalone
#====================================
CMD ["/opt/bin/selenium_standalone.sh"]

USER seluser

EXPOSE 4444
